
FROM ctfd/ctfd:3.5.3

WORKDIR /opt/CTFd
COPY --chown=1001:1001 . .

# hadolint ignore=DL3008

# TODO Won't run as non root user
# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#         build-essential \
#         libffi-dev \
#         libssl-dev \
#         git \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/* \
#     && python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY . /opt/CTFd/plugins/llm_verification

RUN pip install --no-cache-dir -r requirements.txt \
    && for d in CTFd/plugins/*; do \
        if [ -f "$d/requirements.txt" ]; then \
            pip install --no-cache-dir -r "$d/requirements.txt";\
        fi; \
    done;

# User already exists
# RUN useradd \
#     --no-log-init \
#     --shell /bin/bash \
#     -u 1001 \
#     ctfd \
#     && mkdir -p /var/log/CTFd /var/uploads \
#     && chown -R 1001:1001 /var/log/CTFd /var/uploads /opt/CTFd \
#     && chmod +x /opt/CTFd/docker-entrypoint.sh

ENV PATH="/opt/venv/bin:$PATH"

USER root
RUN chown -R 1001:1001 /var/log/CTFd /var/uploads /opt/CTFd 
RUN chmod +x /opt/CTFd/plugins/llm_verification/docker-entrypoint.dev.sh

USER 1001
EXPOSE 8000

# LLMV: Modified entrypoint to use development entrypoint.
# ENTRYPOINT ["/opt/CTFd/plugins/llm_verification/development_helpers/docker-entrypoint.dev.sh"]
# ENTRYPOINT ["/opt/CTFd/plugins/llm_verification/docker-entrypoint.dev.sh"]
# ENTRYPOINT ["ls", "-la", "/opt/CTFd/plugins/llm_verification", "&&", "/opt/CTFd/plugins/llm_verification/docker-entrypoint.dev.sh"]
