name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH into Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: 52.15.244.210
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        port: 22
        script: |
          sh $HOME/start.sh
          touch .heartbeat
